### ISSUE TITLE
Auth support for SameSite Changes coming to Browsers and Loading CCP widget on a 3rd Party Domain

### ISSUE THREAD

**Issue by eaddingtonwhite** [amazon-connect/amazon-connect-streams#210]
As of Chrome v80 – to be released Feb 4 -  (and soon to be Firefox and the latest IE) the browsers will be enforcing [SameSite](https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00) cookies by default.  Meaning that if `SameSite` policy is not set on cookies they will by default not be available across third party domains. This is problematic for any developers trying to embed AWS connect widget's on one of their 3rd party domains.
 
Better explanation: https://web.dev/samesite-cookies-explained/#explicitly-state-cookie-usage-with-the-samesite-attribute

The SAML auth flow with AWS connect currently obtains the following auth cookies after SAML auth flow with a API call to

**POST** `https://${ConnectInstance}.awsapps.com/connect/auth/sign-in`

This API call set the 2 following cookies on Response used for authentication on subsequent AWS Connect Calls

**lily-auth-prod-iad**
&&
**lily-auth-refresh-prod-iad**

<img width="1248" alt="Screen Shot 2020-01-13 at 10 23 59 AM" src="https://user-images.githubusercontent.com/5491827/72281400-53f14c80-35ef-11ea-8f69-be97af9dfb3c.png">

As you can see these cookies are being set with _SameSite_ as empty. This causes Chrome in new version to default cookies _SameSite_ policy to `SameSite=Lax` which then will cause these auth cookies to not be sent to the subsequent AWS call to authorize with how the CCP widget is loaded into an IFRAME on a 3rd party domain.

**GET** `https://${ConnnectInstance}.awsapps.com/connect/auth/authorize`

By downloading chrome canary version you can validate this breaks as well as get the following warning saying cookies are being filtered so they will not be sent along with the call to `/connect/auth/authorize` and thus we get a 401 consistently.

<img width="1169" alt="Screen Shot 2020-01-13 at 10 36 45 AM 1" src="https://user-images.githubusercontent.com/5491827/72282559-bcd9c400-35f1-11ea-9cbd-cd345ca45f05.png">

**To Test:**
1) Download Chrome Canary ( https://www.google.com/chrome/canary/ )
2) In your current Chrome type in chrome://flags, and enable SameSite cookies

<img width="1224" alt="Screen Shot 2020-01-13 at 10 56 56 AM" src="https://user-images.githubusercontent.com/5491827/72283382-80a76300-35f3-11ea-9686-d82373d9ca51.png">

Is there any recommendation for developers to work around this or for how to proceed if they are embedding the CCP widget on a custom domain name. This would be a change Amazon would need to make with how they are defaulting cookies on the call to `/connect/auth/sign-in` and set connect auth cookies to `SameSite=None` if they intend to allow end users to embed the aws connect CCP widget on their domains.

**Comment by scoland** [comment]
Thanks for the detailed post!

We are aware of this issue and are working on a solution, stay tuned for an update.

**Comment by hfahlbusch** [comment]
@scoland Will this fix be compatible with "older" amazon-connect-streams versions and done in CCP code or do we need to upgrade our client installations?

Thanks for any information that helps us to prevent outages.

**Comment by jeffaxial** [comment]
@scoland 
Any updates on this fix? We're a week out before this starts to become a problem for users.

Thanks!

**Comment by scoland** [comment]
A fix has been pushed out to ensure CCP won't have any issues after the SameSite update in Chrome 80. We encourage you to download Chrome 80 beta and test out your site. Please let us know if you have any further questions or continue to have issues when testing.

The fix is server-side so it does not require an update to the streams library.

**Comment by jeffaxial** [comment]
@scoland Great! I have tested in Canary and it seems to work. Calls go through fine.

I still get a few warnings about cookies being blocked in the console from awsapps.com. Are these anything to be concerned about?

**Comment by scoland** [comment]
@jeffaxial update to my above comment:

According to this [page](https://www.chromium.org/updates/same-site) there is a 50% chance that you will get the new SameSite rules applied in your browser when using Chrome 80 beta. I would recommend doing the following to ensure you're testing the change properly:

• Navigate to chrome://flags URL and change the "SameSite by default cookies" and "Cookies without SameSite must be secure" flag to "Enabled".  Reload the browser.

**Comment by jeffaxial** [comment]
@scoland Yeah, I set my flag. Connect worked and was not block like before, but I still note some blocked cookie warnings in the console that I'm curious about.

Here are the warnings I'm still seeing:
![image](https://user-images.githubusercontent.com/17830946/73306533-09bcbd80-41e2-11ea-9334-e3694c940180.png)

**Comment by scoland** [comment]
Gotcha, this is because there are other cookies on that domain which are unrelated to the CCP. If CCP is initializing and you are able to make calls this means the auth cookies are getting through successfully.

**Comment by jeffaxial** [comment]
> Gotcha, this is because there are other cookies on that domain which are unrelated to the CCP. If CCP is initializing and you are able to make calls this means the auth cookies are getting through successfully.

Roger that. Thanks for updating.

**Comment by ctwomblyamzn** [comment]
Closing this issue, as the samesite changes have been made and are functioning properly.
